language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8c1
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8c1
  fast_finish: true

install:
  - pip install Django==$DJANGO_VERSION djangorestframework==3.1.1
  - pip install coveralls
script:
  coverage run runtests.py
after_success:
  coveralls
