language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.14
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.10.1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.9.9
    - python: "3.2"
      env: DJANGO_VERSION=1.10.1
    - python: "3.3"
      env: DJANGO_VERSION=1.9.9
    - python: "3.3"
      env: DJANGO_VERSION=1.10.1
  fast_finish: true

install:
  - pip install Django==$DJANGO_VERSION djangorestframework==3.4.6
  - pip install coverage==3.7.1
  - pip install coveralls
script:
  coverage run runtests.py
after_success:
  coveralls
